# Generated by Django 4.2.16 on 2024-12-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('TVS', 'TV Series'), ('Пол.метр.', 'Полнометражный'), ('Кор.метр.', 'Короткометражный')], max_length=50)),
                ('studios', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('duration', models.FloatField()),
                ('quality', models.CharField(choices=[('HD', 'HD'), ('FHD', 'FHD'), ('LOW', 'LOW'), ('2k', '2K')], max_length=100)),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Произведения',
                'verbose_name_plural': 'Произведения',
            },
        ),
    ]
