# Generated by Django 4.2.16 on 2025-03-27 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0002_session_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='session',
            name='owner',
        ),
    ]
