# Generated by Django 4.2.16 on 2024-12-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0002_session'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'Сеансы', 'verbose_name_plural': 'Сеансы'},
        ),
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.CharField(choices=[('Зак.', 'Законнченный'), ('В раз', 'В разработке')], max_length=100),
        ),
    ]
